# Build settings
# markdown: redcarpet
markdown: kramdown
highlighter: rouge

# Site settings
title: "Billowdood"
description: > # this means to ignore newlines until "email:"
   I can write code when i am not sleeping.

email: rodsislas@gmail.com
#blog logo
logo: "/assets/images/author.jpeg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Rodolfo Islas'
author: 'Rodolfo Islas'
author_image: "/assets/images/author.jpeg"

paginate:	5

url: "https://billowdood.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/billowdood
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/billowdood
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
